# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20160724_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lock',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='lock',
            name='is_opened',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lock',
            name='share_id',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='available',
            name='lock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Lock'),
        ),
    ]
