# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20160726_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='nickname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='lock',
            name='owner',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lock',
            name='share_id',
            field=models.CharField(default='', max_length=12),
        ),
    ]
