# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 20:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allow',
            name='user',
        ),
        migrations.AddField(
            model_name='lock',
            name='owner',
            field=models.CharField(default=datetime.datetime(2016, 7, 24, 20, 28, 40, 621000, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Allow',
        ),
    ]
