# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20160725_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available',
            name='lock_id',
        ),
        migrations.RenameField(
            model_name='lock',
            old_name='lock_id',
            new_name='lock_name',
        ),
        migrations.AddField(
            model_name='lock',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lock',
            name='nickname',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='lock',
            name='owner',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.DeleteModel(
            name='Available',
        ),
    ]
