# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20160726_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30)),
                ('lock_inner_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='lock',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='lock',
            name='owner',
        ),
        migrations.AddField(
            model_name='lock',
            name='ip_address',
            field=models.CharField(default='', max_length=30),
        ),
    ]
