# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20160806_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='lock_inner_id',
            new_name='locks',
        ),
    ]
