# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20160806_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockAbsoluteValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_inner_id', models.CharField(max_length=30)),
                ('ip_address', models.CharField(max_length=30)),
                ('is_opened', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lock',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='lock',
            name='is_opened',
        ),
        migrations.AlterField(
            model_name='lock',
            name='lock_inner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.LockAbsoluteValues'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
