# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20160806_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lock',
            old_name='lock_inner_id',
            new_name='lock_id',
        ),
    ]
