# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20160806_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LockAbsoluteValues',
            new_name='LockAbsVal',
        ),
    ]
