# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20160806_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='share_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
